const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const M=require('../scenario-model.js');
const code=fs.readFileSync(require.resolve('../scenario-ui.js'),'utf8');
const ctx=vm.createContext({ScenarioModel:M,f1:x=>Number(x).toFixed(1)});
vm.runInContext(code.slice(code.indexOf('function thresholdLabel'),code.indexOf('async function renderRecommendation')),ctx);
const method=M.methods.find(m=>m.id==='B');
const p={mu:745,sd:15,internalMu:200,internalSd:20,r:0,distribution:'normal',undecided:'exclude',profile:'base'};
const me={c:759,m:207,t:'A'};
const peers=[{c:759,m:207,t:'A'},...Array.from({length:20},(_,i)=>({c:730+i,m:null,t:'B'}))];
const run=M.switchRun(me,peers,p,'B');
const html=ctx.comparisonMarkup(method,[run],true);
assert(html.includes('593.4'));
assert(html.includes('מקום 1.5 מתוך 2'));
assert(html.includes('מתוך 21'));
assert(html.includes('טווח מיקום משוער: <bdi dir="ltr">'));
assert(!/NaN|undefined/.test(html));
assert.equal(ctx.thresholdLabel(Infinity),'לא נמצא עד 250');
const noMor=ctx.comparisonMarkup(method,[M.switchRun({...me,m:null},peers,p,'B')],false);
assert(!noMor.includes('מכסה א׳'));assert(noMor.includes('מכסה ב׳'));
const empty=ctx.comparisonMarkup(method,[M.switchRun(me,[],p,'B')],true);
assert.equal((empty.match(/אין מספיק רשומות לדירוג/g)||[]).length,2);
assert(!empty.includes('מקום 1 מתוך 1'));
assert(ctx.comparisonMarkup(method,[],true).includes('אין מספיק נתונים לחישוב'));
console.log('PASS UI: numeric score, tie rank, group size, RTL range, missing groups, no MOR and unreachable cutoff');
